---
- name: Setting Up Server 1
  hosts: server1
  strategy: free
  ignore_errors: true
  gather_facts: false
  tasks:
  - name: Setting Up Python
    file:
      src: /usr/bin/python3.6
      path: /usr/bin/python
      state: link
  - name: Setting Hostname
    hostname: name=server1.eight.example.com
  - name: Configuring network
    shell: nmcli con mod "System eth1" ipv4.addresses 192.168.56.150/24 ipv4.gateway 192.168.56.1 ipv4.dns 8.8.8.8 ipv4.dns-search eight.example.com ipv4.method manual
  - name: Reloading Network
    service: 
      name: NetworkManager
      state: restarted 
  - name: Building Host File
    copy:
      dest: /etc/hosts
      content: "127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4\n:1         localhost localhost.localdomain localhost6 localhost6.localdomain6\n192.168.56.149 repo.eight.example.com repo\n192.168.56.150 server1.eight.example.com server1\n192.168.56.151 server2.eight.example.com server2"
      force: yes
  - name: Erasing Repos
    file:
      path: /etc/yum.repos.d/*
      state: absent
    become: yes
  - name: Starting services
    service:
      name: "{{ item }}"
      state: started
      enabled: yes
    with_items:
      - firewalld
      - httpd
  - name: Enabling Firewall Services
    firewalld: 
      service: "{{ item }}"
      immediate: yes
      permanent: yes
      state: enabled
    with_items:
      - http 
      - https 
      - ntp 
      - dns
      - ftp
  - name: Reloading Firewall
    service: name=firewalld state=restarted
  - name: Enabling IPV6
    sysctl:
      name: "{{ item }}"
      value: '0'
      sysctl_set: yes
    with_items:
      - net.ipv6.conf.lo.disable_ipv6
      - net.ipv6.conf.all.disable_ipv6
  - name: Changing User Password
    shell: echo vagrant | sudo passwd vagrant --stdin
  - name: Changing Root Password
    shell: echo password | sudo passwd root --stdin
  - name: Creating Welcome Message
    file:
      path: /etc/profile.d/welcome.sh
      state: touch
      mode: 0755
  - name: Building Welcome Message then rebooting
    blockinfile:
      dest: /etc/profile.d/welcome.sh
      block: |
         #!/bin/bash
         #
         echo -e '
         #          _     _        _        _         _           _          _   _        _              
         #         / /\  /\ \     /\_\     / /\      /\ \        /\ \       /\_\/\_\ _   / /\            
         #        / /  \ \ \ \   / / /    / /  \     \_\ \      /  \ \     / / / / //\_\/ /  \           
         #       / / /\ \_\ \ \_/ / /    / / /\ \__  /\__ \    / /\ \ \   /\ \/ \ \/ / /_/ /\ \          
         #      / / /\ \___\ \___/ /    / / /\ \___\/ /_ \ \  / / /\ \_\ /  \____\__/ /\_\/\ \ \         
         #      \ \ \ \/___/\ \ \_/     \ \ \ \/___/ / /\ \ \/ /_/_ \/_// /\/________/      \ \ \        
         #       \ \ \       \ \ \       \ \ \    / / /  \/_/ /____/\  / / /\/_// / /        \ \ \       
         #   _    \ \ \       \ \ \  _    \ \ \  / / /     / /\____\/ / / /    / / /          \ \ \      
         #  /_/\__/ / /        \ \ \/_/\__/ / / / / /     / / /______/ / /    / / /          __\ \ \___  
         #  \ \/___/ /          \ \_\ \/___/ / /_/ /     / / /_______\/_/    / / /          /___\_\/__/\ 
         #   \_____\/            \/_/\_____\/  \_\/      \/__________/       \/_/           \_________\/ 
         #                                                                                               
         '"#
         # You are logged into \"`hostname`\" as the \"`whoami`\" account.
         # This system is running `cat /etc/redhat-release`
         #
         # For root - use \`sudo\` or \`sudo su -\`
         #
         # Repo/AppStream 
         # Available to use from http://repo.eight.example.com/BaseOS 
         # and http://repo.eight.example.com/AppStream
         "
  - name: Adjusting Services and Rebooting
    selinux:
      state: enforcing
      policy: targeted
